# File: motor_interfaces/msg/SetControllerMode.srv
#
# motor_interfaces: ROS 2 package containing custom messages, services and actions for the control of a BLDC motor using SimpleFOC and MicroROS
# SetControllerMode.srv: Service definition for changing the FOC controller operating mode
#
# Description:
# This service changes the operating mode of the SimpleFOC controller.
# There are 7 possible options: position (closed loop), velocity (closed loop), torque, position (open loop), and velocity (open loop).
# The closed loop modes (including torque) use a position sensor, encoder, and/or current sensors to determine the motor shaft position, velocity, or torque* using algorithms.
# The open loop modes relies on tight timing and other algorithms to control a motor without any external inputs.
# Naturally, closed loop control is more accurate and controlled than open loop, but more complex to inegrate.
#
# Request:
# uint8 mode        The desired FOC controller mode. See table below for details
#
# Response:
# uint8 result      Result of the operation. A failure may indicate that the system is in an error state, or a feedback device is not present.
#
# See https://docs.simplefoc.com/motion_control for more details
# Mode | Name
# -----|------------------------
#   0  | Position (closed loop)
#   1  | Velocity (closed loop)
#   3  | Torque (voltage) 
#   4  | Torque (DC current) 
#   5  | Torque (FOC current) 
#   6  | Position (open loop)
#   7  | Velocity (open loop)
#
# Result | Description
# -------|----------------------------
#    0   | Operation success; controller mode changed as requested or controller already in specified mode.
#    1   | Operation failed - unspecified error
#    2   | Operation failed - FOC controller in error mode
#    3   | Operation failed - Feedback device not initialized for control mode

uint8 mode
---
uint8 result