# File: motor_interfaces/msg/SetMotorDirection.srv
#
# motor_interfaces: ROS 2 package containing custom messages, services and actions for the control of a BLDC motor using SimpleFOC and MicroROS
# SetMotorDirection.srv: Service definition for changing the motor direction
#
# Description:
# The motor can spin in two directions (bi-direction) - counter-clockwise (right) or clockwise (left).
# This service changes the motor direction in real time to what is specified in the request body
#
# Request:
# bool direction        The desired motor direction. FALSE - counter-clockwise; TRUE - clockwise
#
# Response:
# bool result           Result of the operation. A failure may indicate that the system is in an error state, or a feedback device is not present.

bool direction 
---
bool result